INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'As the photograph began to affect the way artists represented the world, other experiments were underway.',1);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Cézanne had paved the way for a new kind of painting, one in which the artist was not solely concerned with depicting reality, but with thinking about painting as an object in itself.',2);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'IMPRESSIONISM',3);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Claude Monet',4);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'A French artist born in the 1840s, Monet is the best known of the Impressionist painters, and indeed made the painting which gave the movement its name.',5);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Impression: Sunrise is a small painting of the houses of parliament and the river Thames in London, the water reflecting the oranges and pinks of the sun which is painted as a small orange circle.',6);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'This painting was remarkable at the time for its vagueness in terms of detail, and for the consideration of the nature of the painted surface, so that the sun could have read both as a sun and as a painted circle.',7);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'The English painter Whistler, who was not a fan, claimed the painting to be a \'naïve daubing\'.',8);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Along with Matisse and Picasso, on whom he was influential, Monet considered one of the greatest artists in the world and the three together to be the founders of modernism and 20th century painting.',9);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'With the advent of photography and its apparent challenge to the painter to paint what the eye could see as exactly as possible, Monet championed a different approach.',10);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'He was trying to paint an impression of what he saw, as if with eyes half shut, and it is possible that he got this idea through seeing out of focus photographic mages.',11);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'After all the idea of a deliberately blurred image was a radically new one at the time and Monet\'s idea changed the aims of painters everywhere.',12);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Monet took from Cézanne the idea that an artist might paint what was in front of him but paint less that he actually saw, aiming to reproduce the essence of the view.',13);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'To this end he developed a very distinctive style, breaking the subject he painted into patches of colour and using colour to paint light as well as solid forms.',14);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Monet often left the white ground of the canvas bare in places.',15);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Monet made several important groups of works.',16);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'The Water lily paintings made at his country home in Giverny, the façade of Rouen cathedral, and the haystacks.',17);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'The water lilies series are largely 3 m by 4 m semi abstract canvases which depict a pond or lake with water lilies on it using shades of emerald, ultramarine and violet, with bright pink and red highlights on the usually white lilies.',18);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'The way the paint is applied to construct the image is almost of as much importance as the image itself.',19);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'A series of paintings of the façade of the cathedral at Rouen was a detailed exercise in and demonstration of impressionist technique.',20);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'In these works the surface of the painting is encrusted with multicoloured paint which is visible as a façade only at a distance.',21);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'There are an immense variety of paintings which represent and exaggerated different light conditions.',22);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Monet was unique in his preference for continual repetition of views of the same subject.',23);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'He also painted hay stacks series, notable for their pale blue and lilac shadows, a houses of parliament and Thames series.',24);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Although best known for these series of large scale paintings, Monet made a large number of one off works preceding these.',25);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'The members of the Paris salon rejected the work done by Impressionist artists, leading them to form the Salon des Refuses, a place for all those artists rejected by the Salon to exhibit.',26);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'It was soon clear that these rejected  artists were changing painting for ever and that they were in fact the avant garde',27);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Matisse Henri',28);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'A French painter and sculptor, Matisse is considered one of the greatest artist in the world.',29);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'His paintings include the famous Dance, an 8 metre by 3 metre panoramic painting of dancing female nudes, renowned for its semi abstraction.',30);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'The pink figures become rhythmic arabesques on the swirling blue ground.',31);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Matisse later made these figures into paper cut-outs, a form in which he was prolific in later life, using ultramarine paper collaged onto a white ground.',32);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Along with the Snail, a large 4 by 3 metre collage made of a spiral of squares of different brightly coloured pieces of paper within a yellow collaged frame, these cut-out became perhaps Matisse\'s best known work, their graphic simplicity lending itself well to printed reproduction.',33);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'The blue dancers, their heavy limbs creating a calligraphic pattern, are one of the most recognisable works by a twentieth century artist.',34);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Matisse also did a large number of drawings and had an assured hand, creating very simple drawings often using one continuous line.',35);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'However it is for his figurative painting that he is most greatly respected, his use of drawing within a painting, the way he allowed a drawn edge to define the pictorial space and function both as part of an object or structure and part of the composition, and similarly the way in which he left areas of the canvas unpainted, allowing the white of the ground to function as part of the image.',36);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Matisse painted restful, joyous and domestic subjects in an entirely unsentimental and in fact highly intellectual way.',37);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'His composition was daring, as in the Piano Lesson, a predominantly green and red painting with large blocks of colour, entirely figurative but which nevertheless has an abstract sensibility.',38);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'It is probably the use of colour which singles him out, for example in a head and shoulders portrait of a woman with a green face, in which the shadow of the woman\'s hat over her face is painted in a swoop of emerald green.',39);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Matisse was translating what his eye saw literally into the substance of paint.',40);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Another of his great paintings depicts a goldfish in a bowl on a table by a French window opening onto a tiny balcony.',41);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'The window and room are boldly outlined in black, the goldfish bowl is painted minimally yet very convincingly.',42);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'The Red Studio is a particularly daring work, showing the furniture and objects in his studio outlined in white (made simply by leaving the canvas white where he wanted the line to be) and some colour, with minimal perspective, but chiefly this is a red square of canvas with objects floating on it.',43);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'He also made a number of bronze casts, the best known of which is the triptych The Back, an abstracted human torso viewed from the back, carved in relief as semi cylindrical shapes to represent the two sides of the back and the buttocks, leaving a space in the middle to represent the division caused by the spine.',44);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'The Back sculptures were commissioned for a specific interior and were thus made as three bronze wall reliefs.',45);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'SCULPUTRE IN THE 1960S',46);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Matta Clark Gordon',47);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'An American artist born in 1940s working from 1960s onwards.',48);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Matta Clark is best known for his work House, a suburban clapboard house which the artist cut in two vertically down the centre leaving the two halves leaning outwards and away from each other.',49);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Matta Clark made a number of other works  which involved cutting through buildings, for example a project at the opening of the Pompidou Centre in Paris he cut several circular and elliptical holes through a nearby building that was about to be redeveloped.',50);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Although complex in terms of their execution, Matta Clark\'s interventions are visually extremely simple.',51);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Perry Grayson',52);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'British artist who made ceramic pots and vases richly decorated with drawn images, collaged photographic and printed elements, huge variety of glazes and gold and silver leaf.',53);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Perry\'s pots seem like precious decorative objects but on closer inspection are revealed to bear highly politicised messages about issues that concern the artist for example abuse, refugees or war.',54);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'The juxtaposition of luxury objet d\'art with hard hitting message makes the vases transcend their genre.',55);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Perry is a transvestite who nearly always appears in public as a woman who has number of theatrical identities, for example a Russian babushka and a Victorian lady, (as whom Perry often carries a porcelain doll dressed in a matching costume).',56);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Perry has also made photographic works - as a woman in her various alter egos, and embroideries.',57);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'The costumes themselves are made by Perry and are also part of the work.',58);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Anger Kenneth',59);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Underground filmmaker born in the 50s whose best known film Scorpio Rising had an influence on a whole generation of artists and filmmakers.',60);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'SEVENTIES PERFORMANCE ART',61);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Antin Eleanor',62);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'American artist born around 1948 whose best known work, Carving: a Traditional Sculpture, was made in 1971.',63);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Antin put herself on a strict diet and had a male doctor weigh and measure her every day for a month, on of a number of works in which Antin investigated the effect on women of the ideals forced on them in a patriarchal society.',64);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'In Carving: a Traditional Sculpture Antin attempted to literally sculpt her own body, making a comment both on women\'s control over their own bodies and the centuries of depiction of the nude female body by men, and on women\'s continuing need to make themselves attractive for men.',65);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'The performance was documented by one photograph every day which were placed together in a grid and framed, and by a video.',66);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'During the 1980s Antin began to make more theatrical performances, using cut out puppets and developed an alter ego, Eleanora Antinova a trans gender Russian ballet dancer who wore a tutu and a long beard.',67);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Canaletto',68);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Italian artist who was working in the mid sixteenth century.',69);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'He is world famous for his panoramic scenes of Venice, the grand canal and its palazzos with water traffic passing, painted in very accurate detail and bathed in a golden sunlight.',70);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'He subsequently spent some time in London and painted the Thames river front in a similar way, including the Royal Naval College at Greenwich, St Paul\'s Cathedral.',71);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Canaletto\'s painting are among the most frequently stolen in the world',72);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Bacon Francis',73);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Bacon is a very influential British painter who was born in 1920s and died in the 1990s',74);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'His paintings are conceptual but theatrical figurative works with abstract qualities.',75);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'They are nearly always portraits, in which the figure is distorted, often to grotesque effect, perhaps looking if they have been melted or brushed away, often appearing to be in discomfort with the emphasis on their mouths, usually open and screaming or full of teeth.',76);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'In one painting on an orange ground a figure has an immensely long too thin neck and a head which is largely mouth, upturned and grimacing.',77);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Bacon\'s figures are rendered with rough brushstrokes, and are placed on a contrasting flat colour background, often within a delineated \'three dimensional space\'.',78);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Bacon made many self portraits, one of his best known works is the diptych Three Screaming Popes made around 1960.',79);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Three large canvases each bear a portrait of a pope in a cope and mitre, with blurred and distorted faces, placed within a kind of abstract geometric frame structure, on dark orange and red grounds.',80);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Bacon also painted a dog which is either curled up or chasing its tail, in which as with Bacon\'s other work, there is an impression of movement as if a photograph has been taken on a long exposure and the sitter has moved, leaving a trail of the movement on the image.',81);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Bacon was almost as well know for his lifestyle as for his work: he was a heavy drinking habitué of bars in Soho in London.',82);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Bacon lived a solitary and obsessive working life, rarely spending a day without painting.',83);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'His studio was famously untidy and dirty.',84);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'PIONEERS OF PHOTOGRAPHY',85);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'Atget Eugene',86);
INSERT INTO text (behaviour_id,content,listorder) VALUES (1,'An American photographer of the early 20th century born in 1870s died 1950s',87);
