# phpMyAdmin MySQL-Dump
# version 2.3.0
# http://phpwizard.net/phpMyAdmin/
# http://www.phpmyadmin.net/ (download page)
#
# Host: localhost
# Generation Time: Oct 22, 2003 at 11:22 PM
# Server version: 4.00.14
# PHP Version: 4.3.1
# Database : `svg`
# --------------------------------------------------------

#
# Table structure for table `text`
#

DROP TABLE IF EXISTS `text`;
CREATE TABLE `text` (
  `text_id` int(11) NOT NULL auto_increment,
  `content` longtext,
  `width` int(11) NOT NULL default '350',
  `lines` tinyint(3) NOT NULL default '1',
  `listorder` tinyint(4) NOT NULL default '0',
  `behaviour_id` int(11) default NULL,
  PRIMARY KEY  (`text_id`)
) TYPE=MyISAM;

#
# Dumping data for table `text`
#

INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (29, 'Manzanelli paints young women often dressed like girls, often emaciated but fashionably dressed, a kind of dreamlike heroin chic, in the middle of a large canvas with a plain flat background.', 350, 1, 15, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (28, 'Andrea Mantegna was an Italain renaissance painter.', 350, 1, 12, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (18, 'She provided a number of implements with which to do this including knives and a gun.', 350, 1, 3, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (17, 'Born 1950s, Abramovic first came to public attention when she invited visitors to a gallery in which she appeared naked, stating that the visitors could do anything they wanted to her and she would not resist or retaliate.', 350, 1, 2, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (19, 'She narrowly avoided serious injury but her initial premise was correct: like the invisible barrier of etiquette surrounding an art work, there was a barrier of propriety and embarrassment protecting her that was only broached when the beginnings of a mob mentality formed.', 350, 1, 4, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (20, 'Abramovic worked together with her partner Ulay until the early 1980s making performance \'sculptures\' and endurance works.', 350, 1, 5, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (21, '\'Breathe\' involved them in a mouth to mouth embrace for as long as they could breathe using their combined exhaled breath. They braided their hair together and stayed sitting back to back for eight hours.', 350, 1, 6, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (22, 'For another work they used a full size bow and arrow and stood facing each other, with Ulay holding the string and Abramovic holding the arrow at the point on the centre of the bow string from which it is released.', 350, 1, 7, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (23, 'They maintained this state of equilibrium through tension until the strain of holding on meant they had to stop or let go of the tension in the bow which would have resulted in the release of the arrow which was aimed at Abramovic.', 350, 1, 8, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (24, 'In a work called Doorway they stood naked either side of the entrance to the gallery in the doorway facing each other. This meant that those wishing to enter were forced to brush past them and had to choose who to face as they turned sideways to enter.', 350, 1, 9, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (25, 'These partner works focused on endurance through concentration and on the tension in partnerships as it is manifested in physical mutual support. They are notable for the degree of politeness and gentleness combined with a power and implicit violence.', 350, 1, 10, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (26, 'The artists described them as sculptors.', 350, 1, 11, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (27, 'After the relationship with Ulay ended Abramovic continued to make endurance works but while these maintained a formal sculptural quality they acquired a ritual aspect, as in the work in which she sat in a circle of salt surrounded by poisonous snakes and a work made in an amethyst mining town in Brazil for which she made and wore clogs from blocks of amethyst.', 350, 1, 12, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (30, 'Characterised by their monochrome flat backgrounds, the women usually have painfully thin bodies and large often bulging eyes.', 350, 1, 16, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (31, 'Margarita Manzanelli is an Italian painter born in 1970s.', 350, 1, 15, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (32, 'Robert Mapplethorp was a photographer working in New York in the 1980s and early 90s.', 350, 1, 17, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (33, 'Mapplethorp became notorious for his photographs of gay men, often naked, sexually unambiguous such as Man in a Polyester Suit which shows an African-american man in the eponymous suit resting his penis on a stool, and another photograph showing a man urinating into another\'s mouth, both men dressed in leather.', 350, 1, 18, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (34, 'Photographs like these led to him being attacked by the Christian right and his exhibitions denounced as pornography.', 350, 1, 19, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (37, 'The fact that museums spent public money on exhibiting Mapplethorp\'s work led to a full scale row in the United States senate and other artists were dragged into the debate.', 350, 1, 20, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (38, 'Senator Jesse Helms led the attack supported by The Association for the American Family and religious organisations.', 350, 1, 21, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (39, 'The result was a substantial decrease in the amount of support given to artist by the National Endowment for the Arts, the United States government arts subsidy.', 350, 1, 22, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (40, 'As well as a questioning of the definition of obscenity laws and a revision of the censorship laws making it easier to close an exhibition or require special conditions to be met.', 350, 1, 23, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (41, 'There were many counter claims of discrimination on the grounds of sexuality.', 350, 1, 24, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (42, 'Mapplethorp said of his work that he photographed images of love and trust, and that even the most \'sado masochistic\' of his images represented supreme trust, love and vulnerability on the part of the participants.', 350, 1, 25, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (43, 'His defenders claimed that if his images were of heterosexual couples there would have been no such outcry.', 350, 1, 26, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (44, 'The case went to court and a ruling was made that the photographs defined as obscene could only be exhibited in a specially constructed screened off area, with a clear indication to the public of the contents of the these works.', 350, 1, 27, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (45, 'The case increased the public interest in the work and made Mapplethorp one of the best known photographers in the world.', 350, 1, 28, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (46, 'Mapplethorp\'s themes were (like many gay artists of the period in which so many were lost to AIDS) love, sex and death.', 350, 1, 29, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (47, 'He made many self portraits including the best known in which he wears a leather biker jacket and a leather cap, one as a young man with Patti Smith the singer on a fire escape, right up until his death, including one in which he is visibly frail and  holds a cane topped with a skull and crossbones emblem which owes an allegiance to Warhol\'s late self portraits.', 350, 1, 30, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (48, 'Mapplethorp made a series of photographs of flowers which also represent sexuality.', 350, 1, 31, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (49, 'He photographed lilies and other exotic flowers in the studio, these were sometimes reminiscent of Georgia O\'Keefe paintings usually black and white but some coloured.', 350, 1, 32, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (50, 'Mapplethorp also photographed the body builder Lisa Lyon, whose physique he considered to be perfect and made commissioned portraits, for which he was much sought after by the rich and famous.', 350, 1, 33, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (51, 'Robert Mapplethorp died of AIDS in 1994.', 350, 1, 34, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (52, 'THE RENAISSANCE PERIOD', 350, 1, 1, 2);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (53, 'As the photograph began to affect the way artists represented the world, other experiments were underway.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (54, 'Cézanne had paved the way for a new kind of painting, one in which the artist was not solely concerned with depicting reality, but with thinking about painting as an object in itself.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (55, 'IMPRESSIONISM', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (56, 'Claude Monet', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (57, 'A French artist born in the 1840s, Monet is the best known of the Impressionist painters, and indeed made the painting which gave the movement its name.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (58, 'Impression: Sunrise is a small painting of the houses of parliament and the river Thames in London, the water reflecting the oranges and pinks of the sun which is painted as a small orange circle.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (59, 'This painting was remarkable at the time for its vagueness in terms of detail, and for the consideration of the nature of the painted surface, so that the sun could have read both as a sun and as a painted circle.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (60, 'The English painter Whistler, who was not a fan, claimed the painting to be a \'naïve daubing\'.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (61, 'Along with Matisse and Picasso, on whom he was influential, Monet considered one of the greatest artists in the world and the three together to be the founders of modernism and 20th century painting.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (62, 'With the advent of photography and its apparent challenge to the painter to paint what the eye could see as exactly as possible, Monet championed a different approach.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (63, 'He was trying to paint an impression of what he saw, as if with eyes half shut, and it is possible that he got this idea through seeing out of focus photographic mages.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (64, 'After all the idea of a deliberately blurred image was a radically new one at the time and Monet\'s idea changed the aims of painters everywhere.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (65, 'Monet took from Cézanne the idea that an artist might paint what was in front of him but paint less that he actually saw, aiming to reproduce the essence of the view.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (66, 'To this end he developed a very distinctive style, breaking the subject he painted into patches of colour and using colour to paint light as well as solid forms.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (67, 'Monet often left the white ground of the canvas bare in places.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (68, 'Monet made several important groups of works.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (69, 'The Water lily paintings made at his country home in Giverny, the façade of Rouen cathedral, and the haystacks.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (70, 'The water lilies series are largely 3 m by 4 m semi abstract canvases which depict a pond or lake with water lilies on it using shades of emerald, ultramarine and violet, with bright pink and red highlights on the usually white lilies.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (71, 'The way the paint is applied to construct the image is almost of as much importance as the image itself.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (72, 'A series of paintings of the façade of the cathedral at Rouen was a detailed exercise in and demonstration of impressionist technique.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (73, 'In these works the surface of the painting is encrusted with multicoloured paint which is visible as a façade only at a distance.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (74, 'There are an immense variety of paintings which represent and exaggerated different light conditions.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (75, 'Monet was unique in his preference for continual repetition of views of the same subject.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (76, 'He also painted hay stacks series, notable for their pale blue and lilac shadows, a houses of parliament and Thames series.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (77, 'Although best known for these series of large scale paintings, Monet made a large number of one off works preceding these.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (78, 'The members of the Paris salon rejected the work done by Impressionist artists, leading them to form the Salon des Refuses, a place for all those artists rejected by the Salon to exhibit.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (79, 'It was soon clear that these rejected  artists were changing painting for ever and that they were in fact the avant garde', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (80, 'Matisse Henri', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (81, 'A French painter and sculptor, Matisse is considered one of the greatest artist in the world.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (82, 'His paintings include the famous Dance, an 8 metre by 3 metre panoramic painting of dancing female nudes, renowned for its semi abstraction.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (83, 'The pink figures become rhythmic arabesques on the swirling blue ground.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (84, 'Matisse later made these figures into paper cut-outs, a form in which he was prolific in later life, using ultramarine paper collaged onto a white ground.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (85, 'Along with the Snail, a large 4 by 3 metre collage made of a spiral of squares of different brightly coloured pieces of paper within a yellow collaged frame, these cut-out became perhaps Matisse\'s best known work, their graphic simplicity lending itself well to printed reproduction.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (86, 'The blue dancers, their heavy limbs creating a calligraphic pattern, are one of the most recognisable works by a twentieth century artist.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (87, 'Matisse also did a large number of drawings and had an assured hand, creating very simple drawings often using one continuous line.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (88, 'However it is for his figurative painting that he is most greatly respected, his use of drawing within a painting, the way he allowed a drawn edge to define the pictorial space and function both as part of an object or structure and part of the composition, and similarly the way in which he left areas of the canvas unpainted, allowing the white of the ground to function as part of the image.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (89, 'Matisse painted restful, joyous and domestic subjects in an entirely unsentimental and in fact highly intellectual way.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (90, 'His composition was daring, as in the Piano Lesson, a predominantly green and red painting with large blocks of colour, entirely figurative but which nevertheless has an abstract sensibility.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (91, 'It is probably the use of colour which singles him out, for example in a head and shoulders portrait of a woman with a green face, in which the shadow of the woman\'s hat over her face is painted in a swoop of emerald green.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (92, 'Matisse was translating what his eye saw literally into the substance of paint.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (93, 'Another of his great paintings depicts a goldfish in a bowl on a table by a French window opening onto a tiny balcony.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (94, 'The window and room are boldly outlined in black, the goldfish bowl is painted minimally yet very convincingly.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (95, 'The Red Studio is a particularly daring work, showing the furniture and objects in his studio outlined in white (made simply by leaving the canvas white where he wanted the line to be) and some colour, with minimal perspective, but chiefly this is a red square of canvas with objects floating on it.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (96, 'He also made a number of bronze casts, the best known of which is the triptych The Back, an abstracted human torso viewed from the back, carved in relief as semi cylindrical shapes to represent the two sides of the back and the buttocks, leaving a space in the middle to represent the division caused by the spine.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (97, 'The Back sculptures were commissioned for a specific interior and were thus made as three bronze wall reliefs.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (98, 'SCULPUTRE IN THE 1960S', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (99, 'Matta Clark Gordon', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (100, 'An American artist born in 1940s working from 1960s onwards.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (101, 'Matta Clark is best known for his work House, a suburban clapboard house which the artist cut in two vertically down the centre leaving the two halves leaning outwards and away from each other.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (102, 'Matta Clark made a number of other works  which involved cutting through buildings, for example a project at the opening of the Pompidou Centre in Paris he cut several circular and elliptical holes through a nearby building that was about to be redeveloped.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (103, 'Although complex in terms of their execution, Matta Clark\'s interventions are visually extremely simple.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (104, 'Perry Grayson', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (105, 'British artist who made ceramic pots and vases richly decorated with drawn images, collaged photographic and printed elements, huge variety of glazes and gold and silver leaf.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (106, 'Perry\'s pots seem like precious decorative objects but on closer inspection are revealed to bear highly politicised messages about issues that concern the artist for example abuse, refugees or war.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (107, 'The juxtaposition of luxury objet d\'art with hard hitting message makes the vases transcend their genre.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (108, 'Perry is a transvestite who nearly always appears in public as a woman who has number of theatrical identities, for example a Russian babushka and a Victorian lady, (as whom Perry often carries a porcelain doll dressed in a matching costume).', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (109, 'Perry has also made photographic works - as a woman in her various alter egos, and embroideries.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (110, 'The costumes themselves are made by Perry and are also part of the work.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (111, 'Anger Kenneth', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (112, 'Underground filmmaker born in the 50s whose best known film Scorpio Rising had an influence on a whole generation of artists and filmmakers.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (113, 'SEVENTIES PERFORMANCE ART', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (114, 'Antin Eleanor', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (115, 'American artist born around 1948 whose best known work, Carving: a Traditional Sculpture, was made in 1971.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (116, 'Antin put herself on a strict diet and had a male doctor weigh and measure her every day for a month, on of a number of works in which Antin investigated the effect on women of the ideals forced on them in a patriarchal society.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (117, 'In Carving: a Traditional Sculpture Antin attempted to literally sculpt her own body, making a comment both on women\'s control over their own bodies and the centuries of depiction of the nude female body by men, and on women\'s continuing need to make themselves attractive for men.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (118, 'The performance was documented by one photograph every day which were placed together in a grid and framed, and by a video.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (119, 'During the 1980s Antin began to make more theatrical performances, using cut out puppets and developed an alter ego, Eleanora Antinova a trans gender Russian ballet dancer who wore a tutu and a long beard.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (120, 'Canaletto', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (121, 'Italian artist who was working in the mid sixteenth century.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (122, 'He is world famous for his panoramic scenes of Venice, the grand canal and its palazzos with water traffic passing, painted in very accurate detail and bathed in a golden sunlight.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (123, 'He subsequently spent some time in London and painted the Thames river front in a similar way, including the Royal Naval College at Greenwich, St Paul\'s Cathedral.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (124, 'Canaletto\'s painting are among the most frequently stolen in the world', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (125, 'Bacon Francis', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (126, 'Bacon is a very influential British painter who was born in 1920s and died in the 1990s', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (127, 'His paintings are conceptual but theatrical figurative works with abstract qualities.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (128, 'They are nearly always portraits, in which the figure is distorted, often to grotesque effect, perhaps looking if they have been melted or brushed away, often appearing to be in discomfort with the emphasis on their mouths, usually open and screaming or full of teeth.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (129, 'In one painting on an orange ground a figure has an immensely long too thin neck and a head which is largely mouth, upturned and grimacing.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (130, 'Bacon\'s figures are rendered with rough brushstrokes, and are placed on a contrasting flat colour background, often within a delineated \'three dimensional space\'.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (131, 'Bacon made many self portraits, one of his best known works is the diptych Three Screaming Popes made around 1960.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (132, 'Three large canvases each bear a portrait of a pope in a cope and mitre, with blurred and distorted faces, placed within a kind of abstract geometric frame structure, on dark orange and red grounds.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (133, 'Bacon also painted a dog which is either curled up or chasing its tail, in which as with Bacon\'s other work, there is an impression of movement as if a photograph has been taken on a long exposure and the sitter has moved, leaving a trail of the movement on the image.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (134, 'Bacon was almost as well know for his lifestyle as for his work: he was a heavy drinking habitué of bars in Soho in London.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (135, 'Bacon lived a solitary and obsessive working life, rarely spending a day without painting.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (136, 'His studio was famously untidy and dirty.', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (137, 'PIONEERS OF PHOTOGRAPHY', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (138, 'Atget Eugene', 350, 1, 0, 1);
INSERT INTO `text` (`text_id`, `content`, `width`, `lines`, `listorder`, `behaviour_id`) VALUES (139, 'An American photographer of the early 20th century born in 1870s died 1950s', 350, 1, 0, 1);

